services:
  # Serviço para a API .NET
  api:
    build:
      context: ./bris-API
      dockerfile: Dockerfile
    ports:
      - "5000:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production  # ambiente para a api
    depends_on:
      - db
    networks:
      - bris-net

# Serviço de migrations
  migrations:
      image: mcr.microsoft.com/dotnet/sdk:8.0  # Usar a imagem SDK
      working_dir: /src
      volumes:
        - ./bris-API:/src  # Montar o código fonte da API
      entrypoint: ["dotnet", "ef", "database", "update"]
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
      depends_on:
        - db
      networks:
        - bris-net

  # Serviço para o Frontend React
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5432:80" 
    environment:
      - NODE_ENV=production # ambiente para o frontend
    networks:
      - bris-net

  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:15.7
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bris_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - bris-net

networks:
  bris-net:
    driver: bridge

volumes:
  postgres_data:
