# Estágio: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Cache de dependências
COPY ["*.csproj", "./"]
RUN dotnet restore

# Instalação do EF Core CLI
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

# Build da aplicação
COPY . .
RUN dotnet build -c Release

# Script de entrada universal
COPY entrypoint_migrations.sh .
RUN chmod +x entrypoint_migrations.sh

ENTRYPOINT ["./entrypoint_migrations.sh"]