worker_processes 1;

events { 
    worker_connections 1024; 
}

http {
    include       mime.types;
    default_type application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    server {
        listen       80;  # Escuta na porta 80
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;  # Diretório onde os arquivos estáticos estão localizados
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;  # Redireciona para index.html em caso de 404
        }

        location ~ /\.ht {
            deny  all;  # Não permitir acesso a arquivos ocultos
        }
    }
}
