// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bris_API.Data;

#nullable disable

namespace bris_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240827211248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bris_API.Models.Agroindustria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJAgroindustria")
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agroindustrias");
                });

            modelBuilder.Entity("bris_API.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GranjaId")
                        .HasColumnType("integer");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Linhagem")
                        .HasColumnType("text");

                    b.Property<int>("Peso")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("UsuarioResponsavelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GranjaId");

                    b.HasIndex("UsuarioResponsavelId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("bris_API.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataInicioAvaliacap")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ResultadoFinal")
                        .HasColumnType("boolean");

                    b.Property<int>("StatusAvaliacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("bris_API.Models.Dose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataResgistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("SemanaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<float>("ValorRegistrado")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SemanaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Doses");
                });

            modelBuilder.Entity("bris_API.Models.Granja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgroindustriaId")
                        .HasColumnType("integer");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Nome_propriedade")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgroindustriaId");

                    b.ToTable("Granjas");
                });

            modelBuilder.Entity("bris_API.Models.Granja_Usuario_Tipo", b =>
                {
                    b.Property<int>("GranjaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("GranjaId", "UsuarioId", "TipoUsuarioId");

                    b.HasIndex("TipoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Granjas_Usuarios_Tipos");
                });

            modelBuilder.Entity("bris_API.Models.Semana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("NroSemana")
                        .HasColumnType("integer");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("Semanas");
                });

            modelBuilder.Entity("bris_API.Models.Senha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Senhas");
                });

            modelBuilder.Entity("bris_API.Models.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposUsuario");
                });

            modelBuilder.Entity("bris_API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("bris_API.Models.Animal", b =>
                {
                    b.HasOne("bris_API.Models.Granja", "Granja")
                        .WithMany("Animais")
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithMany("Animais")
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Granja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Avaliacao", b =>
                {
                    b.HasOne("bris_API.Models.Animal", "Animal")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("bris_API.Models.Dose", b =>
                {
                    b.HasOne("bris_API.Models.Semana", "Semana")
                        .WithMany("Doses")
                        .HasForeignKey("SemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithMany("Doses")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semana");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Granja", b =>
                {
                    b.HasOne("bris_API.Models.Agroindustria", "Agroindustria")
                        .WithMany("Granjas")
                        .HasForeignKey("AgroindustriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agroindustria");
                });

            modelBuilder.Entity("bris_API.Models.Granja_Usuario_Tipo", b =>
                {
                    b.HasOne("bris_API.Models.Granja", "Granja")
                        .WithMany("Granjas_Usuarios_Tipos")
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bris_API.Models.TipoUsuario", "TipoUsuario")
                        .WithMany("Granjas_Usuarios_Tipos")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithMany("Granjas_Usuarios_Tipos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Granja");

                    b.Navigation("TipoUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Semana", b =>
                {
                    b.HasOne("bris_API.Models.Avaliacao", "Avaliacao")
                        .WithMany("Semanas")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("bris_API.Models.Senha", b =>
                {
                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithOne("Senha")
                        .HasForeignKey("bris_API.Models.Senha", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Usuario", b =>
                {
                    b.HasOne("bris_API.Models.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("bris_API.Models.Agroindustria", b =>
                {
                    b.Navigation("Granjas");
                });

            modelBuilder.Entity("bris_API.Models.Animal", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("bris_API.Models.Avaliacao", b =>
                {
                    b.Navigation("Semanas");
                });

            modelBuilder.Entity("bris_API.Models.Granja", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Granjas_Usuarios_Tipos");
                });

            modelBuilder.Entity("bris_API.Models.Semana", b =>
                {
                    b.Navigation("Doses");
                });

            modelBuilder.Entity("bris_API.Models.TipoUsuario", b =>
                {
                    b.Navigation("Granjas_Usuarios_Tipos");
                });

            modelBuilder.Entity("bris_API.Models.Usuario", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Doses");

                    b.Navigation("Granjas_Usuarios_Tipos");

                    b.Navigation("Senha");
                });
#pragma warning restore 612, 618
        }
    }
}
