// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bris_API.Data;

#nullable disable

namespace bris_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250513161159_SeedTestData")]
    partial class SeedTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bris_API.Models.Agroindustria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Agroindustrias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CNPJ = "00000000000101",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4504),
                            Email = "agro_teste@gomail.com",
                            Endereco = "Rua teste 1",
                            NomeFantasia = "Agroindustria Teste",
                            RazaoSocial = "Agroindustria Default",
                            Telefone = "62999999911"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CNPJ = "11111111000102",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4512),
                            Email = "agro_nova@gomail.com",
                            Endereco = "Rua teste 2",
                            NomeFantasia = "Agroindustria Nova",
                            RazaoSocial = "Agroindustria Nova",
                            Telefone = "62999999911"
                        });
                });

            modelBuilder.Entity("bris_API.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GranjaId")
                        .HasColumnType("integer");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Linhagem")
                        .HasColumnType("text");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("UsuarioResponsavelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GranjaId");

                    b.HasIndex("UsuarioResponsavelId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("bris_API.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataInicioAvaliacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProximaDoseOrdem")
                        .HasColumnType("integer");

                    b.Property<int>("ProximaDoseSemana")
                        .HasColumnType("integer");

                    b.Property<bool?>("ResultadoFinal")
                        .HasColumnType("boolean");

                    b.Property<int>("StatusAvaliacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("bris_API.Models.Dose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<bool>("PodePreencher")
                        .HasColumnType("boolean");

                    b.Property<int>("SemanaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<float?>("ValorRegistrado")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SemanaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Doses");
                });

            modelBuilder.Entity("bris_API.Models.Granja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgroindustriaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("NomePropriedade")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgroindustriaId");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Granjas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgroindustriaId = 1,
                            Ativo = true,
                            CNPJ = "99999999000111",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4639),
                            Email = "granja_teste1@gomail.com",
                            NomePropriedade = "Granja Teste 1",
                            Telefone = "62999999921"
                        },
                        new
                        {
                            Id = 2,
                            AgroindustriaId = 1,
                            Ativo = true,
                            CNPJ = "99999999000112",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4644),
                            Email = "granja_teste2@gomail.com",
                            NomePropriedade = "Granja Teste 2",
                            Telefone = "62999999922"
                        },
                        new
                        {
                            Id = 3,
                            AgroindustriaId = 2,
                            Ativo = true,
                            CNPJ = "88888888000121",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4647),
                            Email = "granja_nova1@gomail.com",
                            NomePropriedade = "Granja Nova 1",
                            Telefone = "62999999931"
                        },
                        new
                        {
                            Id = 4,
                            AgroindustriaId = 2,
                            Ativo = true,
                            CNPJ = "88888888000122",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4650),
                            Email = "granja_nova2@gomail.com",
                            NomePropriedade = "Granja Nova 2",
                            Telefone = "62999999932"
                        });
                });

            modelBuilder.Entity("bris_API.Models.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Policy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Policy para VisualizaTotal",
                            Nome = "VisualizaTotal"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Policy para VisualizaAgroindustria",
                            Nome = "VisualizaAgroindustria"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Policy para VisualizaUsuarios",
                            Nome = "VisualizaUsuarios"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Policy para VisualizaAnimais",
                            Nome = "VisualizaAnimais"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Policy para GerenciaTotal",
                            Nome = "GerenciaTotal"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Policy para GerenciaAgroindustria",
                            Nome = "GerenciaAgroindustria"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Policy para GerenciaUsuarios",
                            Nome = "GerenciaUsuarios"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Policy para GerenciaAnimais",
                            Nome = "GerenciaAnimais"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Policy para TodosUsuarios",
                            Nome = "TodosUsuarios"
                        });
                });

            modelBuilder.Entity("bris_API.Models.PolicyRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PolicyId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RoleId");

                    b.ToTable("PolicyRoles");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            PolicyId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            PolicyId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            PolicyId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 25,
                            PolicyId = 2,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 31,
                            PolicyId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 32,
                            PolicyId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            PolicyId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 35,
                            PolicyId = 3,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 41,
                            PolicyId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 42,
                            PolicyId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 43,
                            PolicyId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 45,
                            PolicyId = 4,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 44,
                            PolicyId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 51,
                            PolicyId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 61,
                            PolicyId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 62,
                            PolicyId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 71,
                            PolicyId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 72,
                            PolicyId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 73,
                            PolicyId = 7,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 81,
                            PolicyId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 83,
                            PolicyId = 8,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 84,
                            PolicyId = 8,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 91,
                            PolicyId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 92,
                            PolicyId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 93,
                            PolicyId = 9,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 95,
                            PolicyId = 9,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 94,
                            PolicyId = 9,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("bris_API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Administrador do sistema",
                            Nome = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Gestor de agroindústrias",
                            Nome = "GESTOR_AGRO"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Gestor de granjas",
                            Nome = "GESTOR_GRANJA"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Técnico da granja",
                            Nome = "TECNICO"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Usuário com acesso somente de visualização ao sistema",
                            Nome = "VISUALIZADOR"
                        },
                        new
                        {
                            Id = 98,
                            Descricao = "Usuário pendente de ativação",
                            Nome = "PENDENTE"
                        },
                        new
                        {
                            Id = 99,
                            Descricao = "Usuário inativo",
                            Nome = "INATIVO"
                        });
                });

            modelBuilder.Entity("bris_API.Models.Semana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("NroSemana")
                        .HasColumnType("integer");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("Semanas");
                });

            modelBuilder.Entity("bris_API.Models.Senha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Senhas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Salt = "k9OPqqPqqNebyi+17uH3Pg==",
                            SenhaHash = "InC+6axnxVbVlVk1BdF9Mn1vGlfhsh0gzB6Mi35vRHc=",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Salt = "grBDbVdlfIi1dcxHmbQkPA==",
                            SenhaHash = "f+DmjXMUCnBUtLPJedpWLMlwYOLASKcPuDoLU7vOZK4=",
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Salt = "I+lhpCPV7AXgA+M0CLPSpw==",
                            SenhaHash = "YSdAQq/U1g18QvS2pJdqXnFdwgIo5eC3uDqmeAR/RDE=",
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Salt = "d56K7xBokBNFC9TBZ9FKbQ==",
                            SenhaHash = "NhOXWS9FzbSdFXrO6bqMc5tPAzbrHtJE6q/ZZOzWhSk=",
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Salt = "ObLMi+gdZkSRoTZNl79WYQ==",
                            SenhaHash = "fwojFUmlJv95R5K58x0+btX7LBjnkjbdCu5aEzsr3O4=",
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("bris_API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "11111111111",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4716),
                            Email = "admin@gomail.com",
                            Nome = "Admin",
                            Telefone = "62999999901"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "22222222222",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4721),
                            Email = "gestor_agro@gomail.com",
                            Nome = "Gestor Agro",
                            Telefone = "62999999902"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "33333333333",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4724),
                            Email = "gestor_granja@gomail.com",
                            Nome = "Gestor Granja",
                            Telefone = "62999999903"
                        },
                        new
                        {
                            Id = 4,
                            CPF = "44444444444",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4728),
                            Email = "tecnico@gomail.com",
                            Nome = "Tecnico",
                            Telefone = "62999999904"
                        },
                        new
                        {
                            Id = 5,
                            CPF = "55555555555",
                            DataCadastro = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(4731),
                            Email = "visualizador@gomail.com",
                            Nome = "Visualizador",
                            Telefone = "62999999905"
                        });
                });

            modelBuilder.Entity("bris_API.Models.Vinculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgroindustriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GranjaId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgroindustriaId");

                    b.HasIndex("GranjaId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vinculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(6147),
                            RoleId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgroindustriaId = 1,
                            DataCriacao = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(6154),
                            RoleId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            AgroindustriaId = 1,
                            DataCriacao = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(6157),
                            GranjaId = 1,
                            RoleId = 3,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            AgroindustriaId = 1,
                            DataCriacao = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(6159),
                            GranjaId = 1,
                            RoleId = 4,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            AgroindustriaId = 1,
                            DataCriacao = new DateTime(2025, 5, 13, 16, 11, 57, 116, DateTimeKind.Utc).AddTicks(6162),
                            GranjaId = 1,
                            RoleId = 5,
                            UsuarioId = 5
                        });
                });

            modelBuilder.Entity("bris_API.Models.Animal", b =>
                {
                    b.HasOne("bris_API.Models.Granja", "Granja")
                        .WithMany("Animais")
                        .HasForeignKey("GranjaId");

                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithMany("Animais")
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Granja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Avaliacao", b =>
                {
                    b.HasOne("bris_API.Models.Animal", "Animal")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("bris_API.Models.Dose", b =>
                {
                    b.HasOne("bris_API.Models.Semana", "Semana")
                        .WithMany("Doses")
                        .HasForeignKey("SemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithMany("Doses")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semana");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Granja", b =>
                {
                    b.HasOne("bris_API.Models.Agroindustria", "Agroindustria")
                        .WithMany("Granjas")
                        .HasForeignKey("AgroindustriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agroindustria");
                });

            modelBuilder.Entity("bris_API.Models.PolicyRole", b =>
                {
                    b.HasOne("bris_API.Models.Policy", "Policy")
                        .WithMany("PolicyRoles")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bris_API.Models.Role", "Role")
                        .WithMany("PolicyRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("bris_API.Models.Semana", b =>
                {
                    b.HasOne("bris_API.Models.Avaliacao", "Avaliacao")
                        .WithMany("Semanas")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("bris_API.Models.Senha", b =>
                {
                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithOne("Senha")
                        .HasForeignKey("bris_API.Models.Senha", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Vinculo", b =>
                {
                    b.HasOne("bris_API.Models.Agroindustria", "Agroindustria")
                        .WithMany("Vinculos")
                        .HasForeignKey("AgroindustriaId");

                    b.HasOne("bris_API.Models.Granja", "Granja")
                        .WithMany("Vinculos")
                        .HasForeignKey("GranjaId");

                    b.HasOne("bris_API.Models.Role", "Role")
                        .WithMany("Vinculos")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithMany("Vinculos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agroindustria");

                    b.Navigation("Granja");

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Agroindustria", b =>
                {
                    b.Navigation("Granjas");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("bris_API.Models.Animal", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("bris_API.Models.Avaliacao", b =>
                {
                    b.Navigation("Semanas");
                });

            modelBuilder.Entity("bris_API.Models.Granja", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("bris_API.Models.Policy", b =>
                {
                    b.Navigation("PolicyRoles");
                });

            modelBuilder.Entity("bris_API.Models.Role", b =>
                {
                    b.Navigation("PolicyRoles");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("bris_API.Models.Semana", b =>
                {
                    b.Navigation("Doses");
                });

            modelBuilder.Entity("bris_API.Models.Usuario", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Doses");

                    b.Navigation("Senha");

                    b.Navigation("Vinculos");
                });
#pragma warning restore 612, 618
        }
    }
}
