// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bris_API.Data;

#nullable disable

namespace bris_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250505222528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bris_API.Models.Agroindustria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agroindustrias");
                });

            modelBuilder.Entity("bris_API.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GranjaId")
                        .HasColumnType("integer");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Linhagem")
                        .HasColumnType("text");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("UsuarioResponsavelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GranjaId");

                    b.HasIndex("UsuarioResponsavelId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("bris_API.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataInicioAvaliacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProximaDoseOrdem")
                        .HasColumnType("integer");

                    b.Property<int>("ProximaDoseSemana")
                        .HasColumnType("integer");

                    b.Property<bool?>("ResultadoFinal")
                        .HasColumnType("boolean");

                    b.Property<int>("StatusAvaliacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("bris_API.Models.Dose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<bool>("PodePreencher")
                        .HasColumnType("boolean");

                    b.Property<int>("SemanaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<float?>("ValorRegistrado")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SemanaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Doses");
                });

            modelBuilder.Entity("bris_API.Models.Granja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgroindustriaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("NomePropriedade")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgroindustriaId");

                    b.ToTable("Granjas");
                });

            modelBuilder.Entity("bris_API.Models.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("bris_API.Models.PolicyRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PolicyId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RoleId");

                    b.ToTable("PolicyRoles");
                });

            modelBuilder.Entity("bris_API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("bris_API.Models.Semana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("NroSemana")
                        .HasColumnType("integer");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.ToTable("Semanas");
                });

            modelBuilder.Entity("bris_API.Models.Senha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Senhas");
                });

            modelBuilder.Entity("bris_API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("bris_API.Models.Vinculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgroindustriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GranjaId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgroindustriaId");

                    b.HasIndex("GranjaId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vinculos");
                });

            modelBuilder.Entity("bris_API.Models.Animal", b =>
                {
                    b.HasOne("bris_API.Models.Granja", "Granja")
                        .WithMany("Animais")
                        .HasForeignKey("GranjaId");

                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithMany("Animais")
                        .HasForeignKey("UsuarioResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Granja");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Avaliacao", b =>
                {
                    b.HasOne("bris_API.Models.Animal", "Animal")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("bris_API.Models.Dose", b =>
                {
                    b.HasOne("bris_API.Models.Semana", "Semana")
                        .WithMany("Doses")
                        .HasForeignKey("SemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithMany("Doses")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semana");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Granja", b =>
                {
                    b.HasOne("bris_API.Models.Agroindustria", "Agroindustria")
                        .WithMany("Granjas")
                        .HasForeignKey("AgroindustriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agroindustria");
                });

            modelBuilder.Entity("bris_API.Models.PolicyRole", b =>
                {
                    b.HasOne("bris_API.Models.Policy", "Policy")
                        .WithMany("PolicyRoles")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bris_API.Models.Role", "Role")
                        .WithMany("PolicyRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("bris_API.Models.Semana", b =>
                {
                    b.HasOne("bris_API.Models.Avaliacao", "Avaliacao")
                        .WithMany("Semanas")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");
                });

            modelBuilder.Entity("bris_API.Models.Senha", b =>
                {
                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithOne("Senha")
                        .HasForeignKey("bris_API.Models.Senha", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Vinculo", b =>
                {
                    b.HasOne("bris_API.Models.Agroindustria", "Agroindustria")
                        .WithMany("Vinculos")
                        .HasForeignKey("AgroindustriaId");

                    b.HasOne("bris_API.Models.Granja", "Granja")
                        .WithMany("Vinculos")
                        .HasForeignKey("GranjaId");

                    b.HasOne("bris_API.Models.Role", "Role")
                        .WithMany("Vinculos")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bris_API.Models.Usuario", "Usuario")
                        .WithMany("Vinculos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agroindustria");

                    b.Navigation("Granja");

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("bris_API.Models.Agroindustria", b =>
                {
                    b.Navigation("Granjas");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("bris_API.Models.Animal", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("bris_API.Models.Avaliacao", b =>
                {
                    b.Navigation("Semanas");
                });

            modelBuilder.Entity("bris_API.Models.Granja", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("bris_API.Models.Policy", b =>
                {
                    b.Navigation("PolicyRoles");
                });

            modelBuilder.Entity("bris_API.Models.Role", b =>
                {
                    b.Navigation("PolicyRoles");

                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("bris_API.Models.Semana", b =>
                {
                    b.Navigation("Doses");
                });

            modelBuilder.Entity("bris_API.Models.Usuario", b =>
                {
                    b.Navigation("Animais");

                    b.Navigation("Doses");

                    b.Navigation("Senha");

                    b.Navigation("Vinculos");
                });
#pragma warning restore 612, 618
        }
    }
}
